### ISSUE TITLE
How to sample a StateVector input

### ISSUE THREAD

**Issue by tim4431** [Quandela/Perceval#177]
**Prerequisite**
Please ensure this has not been requested on the [Perceval forum](https://perceval.quandela.net/forum)

**Is your feature request related to a problem? Please describe.**
Is perceval package capable of sampling input state defined as a `StateVector` object? I want to sample an input state like $\frac{1}{\sqrt{2}} (|1,0>+|0,1>)$, so I type the code:

```python
p = pcvl.Processor("Naive",circuit)
p.with_input(state_vector)
```
However, it reports:
`NotImplementedError: Could not find signature for with_input: <StateVector>`

It seems that I can only input a `BasisState` object for sampling tasks, and I don't know how to get probability amplitudes and make superposition of them (there is only `sampler.probs()` which is not correct for superposition).

**Comment by tim4431** [comment]
@jsenellart @nicolasheurtel @ericbrts @qu-shaman

**Comment by jsenellart** [comment]
Hello - this is indeed a missing interface, and we will add it up - but you can workaround this way:

```python
p.with_input(pcvl.SVDistribution(state_vector))
```

**Comment by tim4431** [comment]
Thanks for replying, the `SVDistribution` method works!
