### ISSUE TITLE
Make all objects pickable (using pickle)

### ISSUE THREAD

**Issue by Kim-Vallee** [Quandela/Perceval#187]
**Prerequisite**
I have not seen it requested either in github or in the forum.

**Is your feature request related to a problem? Please describe.**
When someone wants to take advantage of the python multiprocessing library, BasicState are not pickable. This is a bit frustrating, since using multiprocessing is sometimes very useful in order to have much faster result. In my project, the BasicState was hidden inside the Processor which held an attribute when called with `with_input` method. Thus it is a bit painful to debug.

**Describe the solution you'd like**
Be able to pickle the states by calling `pickle.dump(pcvl.BasicState([0,1]))` or any other Perceval objects.

**Describe alternatives you've considered**
A simple and effective method would be to implement `__getstate__` and `__setstate__`  as described in [the documentation](https://docs.python.org/3/library/pickle.html#handling-stateful-objects).

**Comment by soupe06** [comment]
Hi Kim,

It is in Perceval's roadmap to parallelize computation, but you may not be able to use pickle. For now, we think about using numba : https://numba.pydata.org/ and it will be seamless for the user. 
Moreover, we work on enhancing backends performances which could also fix your issue.
A third option could be that we help optimize your code, we've worked on similar issues, we could set a discussion for that.

Best regards

Arno
