### ISSUE TITLE
drawSvg 2.0 has a new api, causes import failure

### ISSUE THREAD

**Issue by abdullahkhalids** [Quandela/Perceval#189]
**Prerequisite**
Please ensure that this bug has not been answered on the [Perceval forum](https://perceval.quandela.net/forum) Done

**Describe the bug**
drawsvg (previously drawSvg) has changed its [naming scheme](https://pypi.org/project/drawsvg/) from CamelCase to underscore based, in the 2.0 major release.

Installing drawsvg with version greater than 2.0 causes `import perceval` to fail, because of `import drawSvg` statements in several places. 

**To Reproduce**
1. On a clean system, `python -m pip install perceval-quandela`
2. On the python console `import perceval`
3.  Error relating to `import drawSvg` pops up

**Expected behavior**
Import should occur with no errors.

**Desktop (please complete the following information):**
 - OS: Debian
 - CPU Arch: x86_64
 - Python Version: 3.10
 - Perceval Version: 0.7.3

**Additional context**
The temporary fix is to add `drawsvg<2.0` in the requirements.txt. Long term, perceval should start using the latest version of drawsvg. As many of drawsvg function names have changed, this will require some work.

**Comment by ericbrts** [comment]
Hello,

Thank you for your detailed message.
You're right, drawsvg released a major update last Sunday, breaking its own API.
Perceval will support drawsvg 2.0+ starting from the upcoming 0.8.0 version.

For now, as you proposed, users willing to install new environments with Perceval 0.7.x will have to manually downgrade drawsvg.
This can be done, in command line, as easily as:
`(venv) $ pip install drawsvg<2.0`

Best regards,
Eric

**Comment by abdullahkhalids** [comment]
Thank you. Small correction: one needs quotes to prevent the < be interpreted as a shell redirect operator.
```
pip install "drawsvg<2.0"
```

**Comment by ericbrts** [comment]
Hi,

Perceval 0.8.0 was released last Friday and uses drawsvg 2, fixing this issue for good.

Thanks again for your workaround.
Best regards,
Eric
