### ISSUE TITLE
Qiskit converter appears to fail for Qiskit circuit

### ISSUE THREAD

**Issue by vprusso** [Quandela/Perceval#201]
**Description:**
I'm attempting to take a `qiskit.QuantumCircuit` object that is obtained from the [QFT QED-C benchmark](https://github.com/SRI-International/QC-App-Oriented-Benchmarks/blob/master/quantum-fourier-transform/qiskit/qft_benchmark.py) and use the perceval converter to take that and convert it into something that perceval understands, but the converter appears to be failing.

**Steps to reproduce:**

**Clone QED-C repo:**

```
git clone https://github.com/vprusso/QC-App-Oriented-Benchmarks.git
cd QC-App-Oriented-Benchmarks/
```

**Create virtual env:**
```python -m venv venv```

**Activate virtual env:**
``source venv/bin/activate``

**Install minimal dependencies:**
```
pip install qiskit
pip install perceval-quandela
```

**(Attempt to) run QFT benchmark**
In `QC-App-Oriented-Benchmarks/quantum-fourier-transform/qiskit`, replace the `if __name__ == "__main__"` block with:

```python
    import perceval as pcvl
    from perceval.converters import QiskitConverter
    from perceval.components import catalog

    token_qcloud = '<TOKEN>'

    circuit = QuantumFourierTransform(2, 1)

    # Then convert the Quantum Circuit with Perceval QiskitConvertor
    qiskit_converter = QiskitConverter(catalog, backend_name="Naive")
    quantum_processor = qiskit_converter.convert(circuit)
```

The following error seems to arise:

```
Traceback (most recent call last):
  File "/Users/vincent.russo/Projects/resarch/unitary_fund/metriq-api/benchmark/benchmark/QC-App-Oriented-Benchmarks/quantum-fourier-transform/qiskit/qft_benchmark.py", line 397, in <module>
    quantum_processor = qiskit_converter.convert(circuit)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent.russo/Projects/resarch/unitary_fund/metriq-api/benchmark/venv/lib/python3.11/site-packages/perceval/converters/qiskit_converter.py", line 89, in convert
    assert isinstance(instruction[0], qiskit.circuit.gate.Gate), "cannot convert (%s)" % instruction[0]
AssertionError: cannot convert (Instruction(name='inv_qft', num_qubits=2, num_clbits=0, params=[]))
```

Indeed, the `circuit` variable up above is a `qiskit.QuantumCircuit` object, so, in theory, I believe it should be being fed the right type of argument. 

Is there any type of necessary transpilation that might need to take place? I also attempted to transpile the gates as:

```python
    from qiskit import transpile

    basis_gates = ['u1', 'u2', 'u3', 'cx', 'u']

    qc = QuantumFourierTransform(2, 1)
    qc = transpile(qc, basis_gates=basis_gates)
```

However, this did not seem to work either.

```
Traceback (most recent call last):
  File "/Users/vincent.russo/Projects/resarch/unitary_fund/metriq-api/benchmark/benchmark/QC-App-Oriented-Benchmarks/quantum-fourier-transform/qiskit/qft_benchmark.py", line 395, in <module>
    quantum_processor = qiskit_converter.convert(qc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent.russo/Projects/resarch/unitary_fund/metriq-api/benchmark/venv/lib/python3.11/site-packages/perceval/converters/qiskit_converter.py", line 95, in convert
    p.add(instruction[1][0].index * 2, ins.copy())
  File "/Users/vincent.russo/Projects/resarch/unitary_fund/metriq-api/benchmark/venv/lib/python3.11/site-packages/perceval/components/abstract_processor.py", line 216, in add
    raise RuntimeError("Cannot add any component to a processor with a post-process function. You may remove the post-process function by calling clear_postprocess()")
RuntimeError: Cannot add any component to a processor with a post-process function. You may remove the post-process function by calling clear_postprocess()
```

I know that's a lot of output and content, and if there's anything further I can provide that might be helpful, please do let me know!

**Comment by mbassiouny33** [comment]
The circuit looks like this

![image](https://github.com/Quandela/Perceval/assets/12175103/da4089b5-1b17-4af7-bcef-24de250b81f0)

When the converter goes through the gates and tries to parse them it encounters a black-box gate called "qft", something it does not recognize as one of the native Qiskit (X,S, H, CZ, etc) gates that are supported therefore it fails. (A possible future improvement for the parser is to recognize blocks like this recursively, but atm, custom gates are not supported).

Same when/if you reach `inv_qft`. The easiest solution is to re-implement these as just simple gates, not as a grouped components.

As for the post-process issue, either clear postprocess as the error message indicates or maybe try to disable postselection

```qiskit_converter.convert(circuit, use_postselection=False)```

Hope that helps

**Comment by vprusso** [comment]
Thank you, @mbassiouny33 . I sincerely appreciate the added context and information!
