### ISSUE TITLE
Beautify display of circuits

### ISSUE THREAD

**Issue by jsenellart** [Quandela/Perceval#205]
**Describe the Feature Request**
Renderer of processor produces non aesthetic circuits, where components are not nicely aligned as a human would do. See the attached pictures. The reason is coming from automatic placement of the components that do not take into account global symmetry/semantic of the circuit

**To Reproduce**
In a notebook, or editor with support of matplotlib renderer:

```
import perceval as pcvl
import numpy as np
import random
bs = pcvl.Circuit.generic_interferometer(4,
                                         lambda idx : pcvl.BS(theta=pcvl.P("theta_%d"%idx))//(0, pcvl.PS(phi=np.pi*2*random.random())),
                                         shape="rectangle",
                                         depth = 2*4,
                                         phase_shifter_fun_gen=lambda idx: pcvl.PS(phi=np.pi*2*random.random()))
pcvl.pdisplay(bs)
```

**Expected behavior**
In such interferemoter, we expect some alignement of the beamsplitters that cannot naturally be achieved because of the intermediate phaseshifters

<img width="1205" alt="image" src="https://github.com/Quandela/Perceval/assets/1520492/2b3ffdb6-f222-4d83-8e52-cf009d633cde">

When defining a circuit, we should have a way to give horizontal grid position (`x_grid` in the code below)

```
Circuit(3).add(0, pcvl.BS(), x_grid=1).add(0, pcvl.PS(1), x_grid=2).add(2, pcvl.PS(1), x_grid=2)
```

3) the `x_grid` would be an incremental index not mapping to a specific position but with the following semantic:
   * components with identical `x_grid` should be vertically aligned
   * component A with `x_grid` higher than component B `x_grid` has to be located on its right
   * component with no `x_grid` are flexible (as currently)
4) this additional parameter will be used to beautify circuits generated by `generic_interferometer` and `core_catalog` objects and will be available in the `add` method of `ACircuit` class and child but also in the `add` method of `AProcessor` and child. 

**Additional context**

In notebook, a svg renderer is used (`perceval/rendering/canvas/svg_canvas.py`), in editor, matplotlib renderer is used (`perceval/rendering/canvas/mplot_canvas.py`)

**Comment by FDGod99** [comment]
Hello, I would like to work on this issue. Any tips/suggestions to get started?
