### ISSUE TITLE
power operator is losing annotations

### ISSUE THREAD

**Issue by jsenellart** [Quandela/Perceval#210]
**Describe the bug**
When using power operator on BasicState - annotations got lost

**To Reproduce**
```
>>> s = pcvl.BasicState("|{P:H}>")
>>> print(s)
|{P:H}>
>>>print(s**2)
|{P:H},{P:H}>
>>>print(s*s)
|1,1>
```

**Expected behavior**
`s**2` should be equal to `s*s`

**Comment by ericbrts** [comment]
Issue was completed by @JMaterne

**Comment by jsenellart** [comment]
> Issue was completed by @JMaterne

Thanks for your contribution @JMaterne !

**Comment by JMaterne** [comment]
> > Issue was completed by @JMaterne
> 
> Thanks for your contribution @JMaterne !

Thank you for the opportunity and guidance! :) @jsenellart @ericbrts
