### ISSUE TITLE
Enable selection of simple precision

### ISSUE THREAD

**Issue by jsenellart** [Quandela/Perceval#221]
Currently Perceval uses float64 as a default for storing parameters. For simulation with increasing number of modes/photons, this induces a natural 2x slowdown for numerical precision beyond any QPU native precision.

A nice feature would be to enable a mode in Perceval allowing to switch in simple precision - this could be done with global parameter containing type to use, but will also require exqalibur to accept both simple and double precision calls.

**Comment by ericbrts** [comment]
This is currently being worked on in the `exqalibur` package. We'll come up with a Perceval way of triggering single precision computations when it's ready.
