### ISSUE TITLE
Error in the heralded CNOT in 0.9 version

### ISSUE THREAD

**Issue by asauliere** [Quandela/Perceval#230]
Hello, 
It appears that there is still a problem with the heralded CNOT gate (the one with 8 modes) corrected last week in the 0.9 version. While it computes the right probabilities, I found that the heralded gate is reproducing a control(-X) operation instead of a controlX. I found out while applying my quantum process tomography algorithm on this gate.

I might be wrong, but my algorithm works for the heralded CZ gate in 0.9 version and also for every other 1 qubit and non entangling 2qubit gates. Besides, the heralded CZ gate with H gate on both sides of the target qubit truly implements a controlX operation.

Thanks in advance,

Arman

**Comment by ericbrts** [comment]
Hello Arman,

Thanks for the info. We'll be working on CNOTs right now. I'll keep you updated.

Best wishes,
Eric

**Comment by ericbrts** [comment]
Hello,

The CNOT fix was released in Perceval version 0.9.0.

Thanks,
Eric
