### ISSUE TITLE
Time Delay (TD) element's functionality not implemented

### ISSUE THREAD

**Issue by pvenderbosch** [Quandela/Perceval#28]
In the Hong-Ou-Mandel simulation script, found [here](https://github.com/Quandela/Perceval/blob/677f03808f9fbd3b4390aa4ef8cf6a5e4ec9f83a/scripts/hom-simulation.py), there are two errors.

The first is the initialization of the `AnnotatedBasicState` has incorrect arguments, this can be fixed by transforming the keyword arguments into a list. I changed line 45 to:
```python
st0 = pcvl.AnnotatedBasicState([1, 0], {0: {"time": 2e-9, "time_gen_fn":photon_length_fn}})
```

However, then there still appears an error when I run the script:
```
  File "...\test.py", line 52, in f
    return sim.prob(st0, qc.FockState([2, 0]))+sim.prob(st0, qc.FockState([0, 2]))
  File "...\env\lib\site-packages\perceval\backends\template.py", line 165, in prob
    self.compile(i_state)
  File "...\env\lib\site-packages\perceval\backends\stepper.py", line 96, in compile
    sv.apply_delta_t(r[0], float(c._dt))
AttributeError: 'StateVector' object has no attribute 'apply_delta_t'
```

The line that it fails on is:
https://github.com/Quandela/Perceval/blob/fec53cbc1b73df45c5920e78e836e5ceb8b24d1e/perceval/backends/stepper.py#L96

In the definition of `StateVector` and its parent classes there is no definition of the `apply_delta_t` method.

**Comment by jsenellart** [comment]
Thanks @pvenderbosch - there is a mismatch in the version of this script and the stepper implementation. Fix on the stepper is planned in 0.5.0 that should be released end of next week. I will keep you updated.

**Comment by pvenderbosch** [comment]
Thank you for the information @jsenellart !

**Comment by jsenellart** [comment]
This is now fixed and handled in the last release - see https://github.com/Quandela/Perceval/releases/tag/v0.7.0
