### ISSUE TITLE
Error in the Permutation component

### ISSUE THREAD

**Issue by FGiorgino** [Quandela/Perceval#29]
**Describe the bug**
The matrix of the permutation might not be computed correctly.

**To Reproduce**

```
circuit =  phys.PERM([2, 0, 1])
simulator_backend = pcvl.BackendFactory().get_backend("Naive")
s_circuit = simulator_backend(circuit)
ca = pcvl.CircuitAnalyser(s_circuit, input_states=[pcvl.AnnotatedBasicState("|1,0,0>")], 
                          output_states = [pcvl.AnnotatedBasicState("|0,0,1>"),
                                           pcvl.AnnotatedBasicState("|0,1,0>"), 
                                           pcvl.AnnotatedBasicState("|1,0,0>")])
```
![Perceval_error_2](https://user-images.githubusercontent.com/104494012/169861763-558d25f2-b7e0-4caa-944c-d093c08afc32.png)

As you can see the photon is redirected in the second path while it should be in the third. I looked at the code, in my opinion there is a missing piece here:

https://github.com/Quandela/Perceval/blob/677f03808f9fbd3b4390aa4ef8cf6a5e4ec9f83a/perceval/lib/phys/circuit.py#L386

The unitary u is missing a transposition. Reasoning in physical terms, right now that function correctly describes the permutation only if you reverse the timeline, _i.e._, you invert the input and output states.

The 2-path transposition `phys.PERM([1, 0])` ,  as well as the transposition shown in the [Documentation](https://perceval.quandela.net/docs/_sources/components.rst.txt), produce symmetric matrixes, hence this mistake is not evident. 

 - Perceval Version: 0.4.2

**Comment by jsenellart** [comment]
Thanks @FGiorgino for catching this - fix on its way !
