### ISSUE TITLE
Example for a system of nonlinear differential equations

### ISSUE THREAD

**Issue by anhphuong-ngo** [Quandela/Perceval#375]
**A system of differential equations resolution?**

I'm deeply interested in your work on Perceval, particularly for solving **a nonlinear differential equation** as shown in Section 4.6.3 in your publication: https://perceval.quandela.net/docs/notebooks/Differential_equation_resolution.html

While your example on a single nonlinear differential equation is impressive, I'm curious about its extensible application to **a system of nonlinear differential equations**. Could you provide any guidance or resources on this?
For example:
dx/dt = x−3y+sin(x) 
dy/dt = −x+y−2cos(y)

Thanks!

**Comment by pemeriau** [comment]
Hello! 
We use one phase shifter to iterate on the one-dimensional discretisation of our space. One possibility is to use a second phase shifter to discretize your 2-dimensional space and build the appropriate loss function.

**Comment by anhphuong-ngo** [comment]
@pemeriau Thanks for your reply. I am very impressed by the capabilities of Perceval. As there are not much tutorials and documents for use cases of Perceval in differential equations, it would be very helpful if you could give me more instructions on how to **implement "2-dimensional space and build the appropriate loss function"** as you mentioned.

Look forward to hearing from you. Thanks.

**Comment by pemeriau** [comment]
Hi @anhphuong-ngo 
Unfortunately this is quite an involved (although very interesting) work but there is nothing conceptually different to the 1d case. You should spend some time on this: https://arxiv.org/pdf/2107.05224.pdf and then start with the 1D case already in the documentation, find the appropriate loss function based on the discretisation of your coupled equation and use a 2nd phase shifter to encode the extra dimension.

**Comment by ericbrts** [comment]
Hello,
As this issue does not relate to a technical issue or feature request, I'm closing it.
Thanks.
