### ISSUE TITLE
Pip installation error - cmake

### ISSUE THREAD

**Issue by stared** [Quandela/Perceval#4]
I was excited to install and use it, but it failed at the `pip install` stage.

## System

- MacBook Pro (2021)
- Apple M1 Pro
- macOS 12.2.1 (Monterey)

## Environment

- conda 4.10.3
- Python 3.9.7
- pip-22.0.4

## Error 

`pip install pip install perceval-quandela` I got a message containing:

```
  Building wheel for quandelibc (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
```

## Questions

I assume that `cmake` is needed. Which version to use?

**Comment by jsenellart** [comment]
Hello, yes you do need Cmake that you can simply install with `brew` on macOS (https://brew.sh) - it should work with version 3.4. Current default version installed by `brew` is 3.22. 
Let us know if you have other installation problems !

**Comment by mario-valdivia** [comment]
@stared did you manage to install perceval ?
we'll be releasing binary wheels for Apple M1 soon

**Comment by stared** [comment]
@jsenellart @mario-valdivia Yes, I installed it successfully, and it works!
