### ISSUE TITLE
Unit test modifies access permissions of critical system directory [macOS]

### ISSUE THREAD

**Issue by burlemarxiste** [Quandela/Perceval#403]
As part of the unit test checking persistent data saving and loading, the access permissions of the **parent** directory are changed.

https://github.com/Quandela/Perceval/blob/f6669a0da0c5409c197df241265401b240028972/tests/test_persistent_data.py#L116

On macOS, this changes the permissions of ```/Users/my_user/Library/Application Support/```, which contains settings and data for all other installed applications.

Consequences:
- The system settings directory becomes unreadable if the test aborts (happened on my system).
- Even if the test runs successfully, the permissions are reset to 0o777, giving other users of the system the ability to erase or overwrite settings files.

In addition, 0o755 or 0o700 might be a more reasonable setting than [0o777](https://github.com/Quandela/Perceval/blob/main/tests/test_persistent_data.py#L110) for the folder storing Perceval settings.

Suggested fix: something like pyfakefs if test coverage is essential, if not, excluding the test involving the parent directory?

**Comment by ericbrts** [comment]
Hi, thanks for this issue. We'll look into it ASAP

**Comment by ericbrts** [comment]
Thanks again for pointing that issue - I've removed problematic parts of the tests, and avoided the removal of actual persistent data while running the test.
